"""add course table

Revision ID: 6f2583c137a8
Revises: 2233205a8ecf
Create Date: 2025-08-29 14:40:32.261948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f2583c137a8'
down_revision: Union[str, None] = '2233205a8ecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_course',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'course_id')
    )
    op.alter_column('students', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('teachers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('teachers', 'subject',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'teachers', type_='foreignkey')
    op.drop_column('teachers', 'student_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('student_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'teachers', 'students', ['student_id'], ['id'])
    op.alter_column('teachers', 'subject',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('teachers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('students', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('student_course')
    op.drop_table('courses')
    # ### end Alembic commands ###
